/**
 * This class is generated by jOOQ
 */
package ru.linachan.asgard.orm.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgentData extends org.jooq.impl.TableImpl<ru.linachan.asgard.orm.tables.records.AgentDataRecord> {

	private static final long serialVersionUID = 2034770731;

	/**
	 * The singleton instance of <code>asgard.agent_data</code>
	 */
	public static final ru.linachan.asgard.orm.tables.AgentData AGENT_DATA = new ru.linachan.asgard.orm.tables.AgentData();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<ru.linachan.asgard.orm.tables.records.AgentDataRecord> getRecordType() {
		return ru.linachan.asgard.orm.tables.records.AgentDataRecord.class;
	}

	/**
	 * The column <code>asgard.agent_data.id</code>.
	 */
	public final org.jooq.TableField<ru.linachan.asgard.orm.tables.records.AgentDataRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asgard.agent_data.access_token</code>.
	 */
	public final org.jooq.TableField<ru.linachan.asgard.orm.tables.records.AgentDataRecord, java.lang.String> ACCESS_TOKEN = createField("access_token", org.jooq.impl.SQLDataType.VARCHAR.length(16).nullable(false), this, "");

	/**
	 * The column <code>asgard.agent_data.os_name</code>.
	 */
	public final org.jooq.TableField<ru.linachan.asgard.orm.tables.records.AgentDataRecord, java.lang.String> OS_NAME = createField("os_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asgard.agent_data.os_version</code>.
	 */
	public final org.jooq.TableField<ru.linachan.asgard.orm.tables.records.AgentDataRecord, java.lang.String> OS_VERSION = createField("os_version", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asgard.agent_data.total_ram</code>.
	 */
	public final org.jooq.TableField<ru.linachan.asgard.orm.tables.records.AgentDataRecord, java.lang.Long> TOTAL_RAM = createField("total_ram", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>asgard.agent_data.cpu_name</code>.
	 */
	public final org.jooq.TableField<ru.linachan.asgard.orm.tables.records.AgentDataRecord, java.lang.String> CPU_NAME = createField("cpu_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asgard.agent_data.cpu_cores</code>.
	 */
	public final org.jooq.TableField<ru.linachan.asgard.orm.tables.records.AgentDataRecord, java.lang.Integer> CPU_CORES = createField("cpu_cores", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>asgard.agent_data</code> table reference
	 */
	public AgentData() {
		this("agent_data", null);
	}

	/**
	 * Create an aliased <code>asgard.agent_data</code> table reference
	 */
	public AgentData(java.lang.String alias) {
		this(alias, ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA);
	}

	private AgentData(java.lang.String alias, org.jooq.Table<ru.linachan.asgard.orm.tables.records.AgentDataRecord> aliased) {
		this(alias, aliased, null);
	}

	private AgentData(java.lang.String alias, org.jooq.Table<ru.linachan.asgard.orm.tables.records.AgentDataRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, ru.linachan.asgard.orm.Asgard.ASGARD, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<ru.linachan.asgard.orm.tables.records.AgentDataRecord, java.lang.Integer> getIdentity() {
		return ru.linachan.asgard.orm.Keys.IDENTITY_AGENT_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<ru.linachan.asgard.orm.tables.records.AgentDataRecord> getPrimaryKey() {
		return ru.linachan.asgard.orm.Keys.KEY_AGENT_DATA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<ru.linachan.asgard.orm.tables.records.AgentDataRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<ru.linachan.asgard.orm.tables.records.AgentDataRecord>>asList(ru.linachan.asgard.orm.Keys.KEY_AGENT_DATA_PRIMARY, ru.linachan.asgard.orm.Keys.KEY_AGENT_DATA_UNIQUE_ACCESS_TOKEN);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ru.linachan.asgard.orm.tables.AgentData as(java.lang.String alias) {
		return new ru.linachan.asgard.orm.tables.AgentData(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ru.linachan.asgard.orm.tables.AgentData rename(java.lang.String name) {
		return new ru.linachan.asgard.orm.tables.AgentData(name, null);
	}
}
