/**
 * This class is generated by jOOQ
 */
package ru.linachan.asgard.orm.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskData extends org.jooq.impl.TableImpl<ru.linachan.asgard.orm.tables.records.TaskDataRecord> {

	private static final long serialVersionUID = -225872954;

	/**
	 * The singleton instance of <code>asgard.task_data</code>
	 */
	public static final ru.linachan.asgard.orm.tables.TaskData TASK_DATA = new ru.linachan.asgard.orm.tables.TaskData();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<ru.linachan.asgard.orm.tables.records.TaskDataRecord> getRecordType() {
		return ru.linachan.asgard.orm.tables.records.TaskDataRecord.class;
	}

	/**
	 * The column <code>asgard.task_data.id</code>.
	 */
	public final org.jooq.TableField<ru.linachan.asgard.orm.tables.records.TaskDataRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asgard.task_data.agent_id</code>.
	 */
	public final org.jooq.TableField<ru.linachan.asgard.orm.tables.records.TaskDataRecord, java.lang.Integer> AGENT_ID = createField("agent_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asgard.task_data.task_type</code>.
	 */
	public final org.jooq.TableField<ru.linachan.asgard.orm.tables.records.TaskDataRecord, java.lang.Integer> TASK_TYPE = createField("task_type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asgard.task_data.task_definition</code>.
	 */
	public final org.jooq.TableField<ru.linachan.asgard.orm.tables.records.TaskDataRecord, byte[]> TASK_DEFINITION = createField("task_definition", org.jooq.impl.SQLDataType.BLOB.length(65535), this, "");

	/**
	 * The column <code>asgard.task_data.status</code>.
	 */
	public final org.jooq.TableField<ru.linachan.asgard.orm.tables.records.TaskDataRecord, java.lang.Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asgard.task_data.created_at</code>.
	 */
	public final org.jooq.TableField<ru.linachan.asgard.orm.tables.records.TaskDataRecord, java.lang.Integer> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asgard.task_data.started_at</code>.
	 */
	public final org.jooq.TableField<ru.linachan.asgard.orm.tables.records.TaskDataRecord, java.lang.Integer> STARTED_AT = createField("started_at", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asgard.task_data.finished_at</code>.
	 */
	public final org.jooq.TableField<ru.linachan.asgard.orm.tables.records.TaskDataRecord, java.lang.Integer> FINISHED_AT = createField("finished_at", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asgard.task_data.result</code>.
	 */
	public final org.jooq.TableField<ru.linachan.asgard.orm.tables.records.TaskDataRecord, byte[]> RESULT = createField("result", org.jooq.impl.SQLDataType.BLOB.length(65535), this, "");

	/**
	 * Create a <code>asgard.task_data</code> table reference
	 */
	public TaskData() {
		this("task_data", null);
	}

	/**
	 * Create an aliased <code>asgard.task_data</code> table reference
	 */
	public TaskData(java.lang.String alias) {
		this(alias, ru.linachan.asgard.orm.tables.TaskData.TASK_DATA);
	}

	private TaskData(java.lang.String alias, org.jooq.Table<ru.linachan.asgard.orm.tables.records.TaskDataRecord> aliased) {
		this(alias, aliased, null);
	}

	private TaskData(java.lang.String alias, org.jooq.Table<ru.linachan.asgard.orm.tables.records.TaskDataRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, ru.linachan.asgard.orm.Asgard.ASGARD, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<ru.linachan.asgard.orm.tables.records.TaskDataRecord, java.lang.Integer> getIdentity() {
		return ru.linachan.asgard.orm.Keys.IDENTITY_TASK_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<ru.linachan.asgard.orm.tables.records.TaskDataRecord> getPrimaryKey() {
		return ru.linachan.asgard.orm.Keys.KEY_TASK_DATA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<ru.linachan.asgard.orm.tables.records.TaskDataRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<ru.linachan.asgard.orm.tables.records.TaskDataRecord>>asList(ru.linachan.asgard.orm.Keys.KEY_TASK_DATA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ru.linachan.asgard.orm.tables.TaskData as(java.lang.String alias) {
		return new ru.linachan.asgard.orm.tables.TaskData(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ru.linachan.asgard.orm.tables.TaskData rename(java.lang.String name) {
		return new ru.linachan.asgard.orm.tables.TaskData(name, null);
	}
}
