/**
 * This class is generated by jOOQ
 */
package ru.linachan.asgard.orm.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgentDataRecord extends org.jooq.impl.UpdatableRecordImpl<ru.linachan.asgard.orm.tables.records.AgentDataRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -1685220990;

	/**
	 * Setter for <code>asgard.agent_data.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asgard.agent_data.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asgard.agent_data.access_token</code>.
	 */
	public void setAccessToken(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asgard.agent_data.access_token</code>.
	 */
	public java.lang.String getAccessToken() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>asgard.agent_data.os_name</code>.
	 */
	public void setOsName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asgard.agent_data.os_name</code>.
	 */
	public java.lang.String getOsName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>asgard.agent_data.os_version</code>.
	 */
	public void setOsVersion(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asgard.agent_data.os_version</code>.
	 */
	public java.lang.String getOsVersion() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>asgard.agent_data.total_ram</code>.
	 */
	public void setTotalRam(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asgard.agent_data.total_ram</code>.
	 */
	public java.lang.Long getTotalRam() {
		return (java.lang.Long) getValue(4);
	}

	/**
	 * Setter for <code>asgard.agent_data.cpu_name</code>.
	 */
	public void setCpuName(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asgard.agent_data.cpu_name</code>.
	 */
	public java.lang.String getCpuName() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>asgard.agent_data.cpu_cores</code>.
	 */
	public void setCpuCores(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>asgard.agent_data.cpu_cores</code>.
	 */
	public java.lang.Integer getCpuCores() {
		return (java.lang.Integer) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA.ACCESS_TOKEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA.OS_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA.OS_VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA.TOTAL_RAM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA.CPU_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA.CPU_CORES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getAccessToken();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getOsName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getOsVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getTotalRam();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getCpuName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getCpuCores();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AgentDataRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AgentDataRecord value2(java.lang.String value) {
		setAccessToken(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AgentDataRecord value3(java.lang.String value) {
		setOsName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AgentDataRecord value4(java.lang.String value) {
		setOsVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AgentDataRecord value5(java.lang.Long value) {
		setTotalRam(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AgentDataRecord value6(java.lang.String value) {
		setCpuName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AgentDataRecord value7(java.lang.Integer value) {
		setCpuCores(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AgentDataRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.Long value5, java.lang.String value6, java.lang.Integer value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AgentDataRecord
	 */
	public AgentDataRecord() {
		super(ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA);
	}

	/**
	 * Create a detached, initialised AgentDataRecord
	 */
	public AgentDataRecord(java.lang.Integer id, java.lang.String accessToken, java.lang.String osName, java.lang.String osVersion, java.lang.Long totalRam, java.lang.String cpuName, java.lang.Integer cpuCores) {
		super(ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA);

		setValue(0, id);
		setValue(1, accessToken);
		setValue(2, osName);
		setValue(3, osVersion);
		setValue(4, totalRam);
		setValue(5, cpuName);
		setValue(6, cpuCores);
	}
}
