/**
 * This class is generated by jOOQ
 */
package ru.linachan.asgard.orm.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskDataRecord extends org.jooq.impl.UpdatableRecordImpl<ru.linachan.asgard.orm.tables.records.TaskDataRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.Integer, java.lang.Integer, byte[], java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, byte[]> {

	private static final long serialVersionUID = 936805016;

	/**
	 * Setter for <code>asgard.task_data.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asgard.task_data.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asgard.task_data.agent_id</code>.
	 */
	public void setAgentId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asgard.task_data.agent_id</code>.
	 */
	public java.lang.Integer getAgentId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>asgard.task_data.task_type</code>.
	 */
	public void setTaskType(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asgard.task_data.task_type</code>.
	 */
	public java.lang.Integer getTaskType() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>asgard.task_data.task_definition</code>.
	 */
	public void setTaskDefinition(byte[] value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asgard.task_data.task_definition</code>.
	 */
	public byte[] getTaskDefinition() {
		return (byte[]) getValue(3);
	}

	/**
	 * Setter for <code>asgard.task_data.status</code>.
	 */
	public void setStatus(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asgard.task_data.status</code>.
	 */
	public java.lang.Integer getStatus() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>asgard.task_data.created_at</code>.
	 */
	public void setCreatedAt(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asgard.task_data.created_at</code>.
	 */
	public java.lang.Integer getCreatedAt() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>asgard.task_data.started_at</code>.
	 */
	public void setStartedAt(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>asgard.task_data.started_at</code>.
	 */
	public java.lang.Integer getStartedAt() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>asgard.task_data.finished_at</code>.
	 */
	public void setFinishedAt(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>asgard.task_data.finished_at</code>.
	 */
	public java.lang.Integer getFinishedAt() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>asgard.task_data.result</code>.
	 */
	public void setResult(byte[] value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>asgard.task_data.result</code>.
	 */
	public byte[] getResult() {
		return (byte[]) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.Integer, java.lang.Integer, byte[], java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, byte[]> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.Integer, java.lang.Integer, byte[], java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, byte[]> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return ru.linachan.asgard.orm.tables.TaskData.TASK_DATA.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return ru.linachan.asgard.orm.tables.TaskData.TASK_DATA.AGENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return ru.linachan.asgard.orm.tables.TaskData.TASK_DATA.TASK_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field4() {
		return ru.linachan.asgard.orm.tables.TaskData.TASK_DATA.TASK_DEFINITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return ru.linachan.asgard.orm.tables.TaskData.TASK_DATA.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return ru.linachan.asgard.orm.tables.TaskData.TASK_DATA.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return ru.linachan.asgard.orm.tables.TaskData.TASK_DATA.STARTED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return ru.linachan.asgard.orm.tables.TaskData.TASK_DATA.FINISHED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field9() {
		return ru.linachan.asgard.orm.tables.TaskData.TASK_DATA.RESULT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getAgentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getTaskType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value4() {
		return getTaskDefinition();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getStartedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getFinishedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value9() {
		return getResult();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskDataRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskDataRecord value2(java.lang.Integer value) {
		setAgentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskDataRecord value3(java.lang.Integer value) {
		setTaskType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskDataRecord value4(byte[] value) {
		setTaskDefinition(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskDataRecord value5(java.lang.Integer value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskDataRecord value6(java.lang.Integer value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskDataRecord value7(java.lang.Integer value) {
		setStartedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskDataRecord value8(java.lang.Integer value) {
		setFinishedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskDataRecord value9(byte[] value) {
		setResult(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskDataRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, byte[] value4, java.lang.Integer value5, java.lang.Integer value6, java.lang.Integer value7, java.lang.Integer value8, byte[] value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TaskDataRecord
	 */
	public TaskDataRecord() {
		super(ru.linachan.asgard.orm.tables.TaskData.TASK_DATA);
	}

	/**
	 * Create a detached, initialised TaskDataRecord
	 */
	public TaskDataRecord(java.lang.Integer id, java.lang.Integer agentId, java.lang.Integer taskType, byte[] taskDefinition, java.lang.Integer status, java.lang.Integer createdAt, java.lang.Integer startedAt, java.lang.Integer finishedAt, byte[] result) {
		super(ru.linachan.asgard.orm.tables.TaskData.TASK_DATA);

		setValue(0, id);
		setValue(1, agentId);
		setValue(2, taskType);
		setValue(3, taskDefinition);
		setValue(4, status);
		setValue(5, createdAt);
		setValue(6, startedAt);
		setValue(7, finishedAt);
		setValue(8, result);
	}
}
