/**
 * This class is generated by jOOQ
 */
package ru.linachan.asgard.orm;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Asgard extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -535236763;

	/**
	 * The singleton instance of <code>asgard</code>
	 */
	public static final Asgard ASGARD = new Asgard();

	/**
	 * No further instances allowed
	 */
	private Asgard() {
		super("asgard");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA,
			ru.linachan.asgard.orm.tables.ElementData.ELEMENT_DATA,
			ru.linachan.asgard.orm.tables.TaskData.TASK_DATA);
	}
}
