/**
 * This class is generated by jOOQ
 */
package ru.linachan.asgard.orm;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>asgard</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<ru.linachan.asgard.orm.tables.records.AgentDataRecord, java.lang.Integer> IDENTITY_AGENT_DATA = Identities0.IDENTITY_AGENT_DATA;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<ru.linachan.asgard.orm.tables.records.AgentDataRecord> KEY_AGENT_DATA_PRIMARY = UniqueKeys0.KEY_AGENT_DATA_PRIMARY;
	public static final org.jooq.UniqueKey<ru.linachan.asgard.orm.tables.records.AgentDataRecord> KEY_AGENT_DATA_UNIQUE_ACCESS_TOKEN = UniqueKeys0.KEY_AGENT_DATA_UNIQUE_ACCESS_TOKEN;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<ru.linachan.asgard.orm.tables.records.AgentDataRecord, java.lang.Integer> IDENTITY_AGENT_DATA = createIdentity(ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA, ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<ru.linachan.asgard.orm.tables.records.AgentDataRecord> KEY_AGENT_DATA_PRIMARY = createUniqueKey(ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA, ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA.ID);
		public static final org.jooq.UniqueKey<ru.linachan.asgard.orm.tables.records.AgentDataRecord> KEY_AGENT_DATA_UNIQUE_ACCESS_TOKEN = createUniqueKey(ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA, ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA.ACCESS_TOKEN);
	}
}
