/**
 * This class is generated by jOOQ
 */
package ru.linachan.asgard.orm;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in asgard
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table asgard.agent_data
	 */
	public static final ru.linachan.asgard.orm.tables.AgentData AGENT_DATA = ru.linachan.asgard.orm.tables.AgentData.AGENT_DATA;

	/**
	 * The table asgard.element_data
	 */
	public static final ru.linachan.asgard.orm.tables.ElementData ELEMENT_DATA = ru.linachan.asgard.orm.tables.ElementData.ELEMENT_DATA;

	/**
	 * The table asgard.task_data
	 */
	public static final ru.linachan.asgard.orm.tables.TaskData TASK_DATA = ru.linachan.asgard.orm.tables.TaskData.TASK_DATA;
}
